site_name: Instructions how to use the ELIXIR-TrP-LessonTemplate-MkDocs
nav:
    - About: index.md
    - Setting up a new repository: chapters/chapter_01.md
    - Customize the repository: chapters/chapter_02.md
    - Adding content using GitHub editor: chapters/chapter_03.md
    

theme:
  name: material
  logo: assets/images/white-orange-logo.png
  favicon: assets/images/elixir_favicon.ico
  custom_dir: overrides
  features:
    - navigation.top
    - navigation.footer
    - toc.integrate
  font: 
    text: Lato

# Repository
repo_name: elixir-europe-training/ELIXIR-TrP-LessonTemplateInstructions-MkDocs
repo_url: https://github.com/elixir-europe-training/ELIXIR-TrP-LessonTemplateInstructions-MkDocs
edit_uri: edit/main/docs/

plugins:
  - search
  - bibtex:
      bib_file: "references.bib"
  
# Footer
copyright: Creation of this material was funded by project# and is made availiable under a CC-BY 4.0 licence

markdown_extensions:
  - abbr
  - def_list
  - footnotes
  - tables
  - admonition
  - codehilite:
      guess_lang: false
  - sane_lists
  - smarty
  - toc:
      toc_depth: 3
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

extra_css:
  - stylesheets/extra.css
